name: CI Python Matrix

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Limpiar cache de pip
      run: |
        rm -rf ~/.cache/pip

    - name: Instalar dependencias
      run: pip install -r requirements.txt

    - name: Ejecutar tests
      run: |
        export PYTHONPATH=$PYTHONPATH:.
        pytest tests/ -v

    - name: Verificar app corriendo
      run: |
        timeout 10 python app.py &
        sleep 5
        curl -f http://localhost:5000/health